export const characters = [
    {name: "adventure time",
    text: "Living in the post-apocalyptic land of Ooo, Finn, a 14-year-old boy, and his magical dog, Jake, embark on a series of missions to prove themselves as virtuous adventurers.",
   },
    {name: "Finn the human",
    text: "Finn the Human is the main character of Adventure Time and often appears alongside his best friend and adoptive brother Jake the Dog"},
    {name: "jake the dog",
    text: "Jake the Dog is Finn's best friend and adoptive brother. He is a 28 year old in \"magical dog years\" and a shapeshifting bulldog"},
    {name: "Beemo",
    text: "Beemo is a MO-series video game console system/computer/VCR combo unit who lives with Finn and Jake"},
    {name: "Marceline",
    text: "Marceline the Vampire Queen is a half-human and half-demon vampire, and the eponymous Vampire Queen"},
    {name: "Princess bubblegum",
    text: "Princess Bubblegum is a bubblegum humanoid, comparable to the inhabitants of the Candy Kingdom which she rules."},
    {name: "flame Princess",
    text: "Flame Princess, whose first name is Phoebe, is the 16-year-old princess of the Fire Kingdom, the daughter of the Flame King, and is one of Finn's friends."},
    {name: "Ice King",
    text: "Ice King is a recurring antagonist-turned-supporting protagonist of the series, and is 1,043 years old"},
    {name: "Lemongrab",
    text: "Lemongrab is socially dysfunctional, and has trouble interacting with Candy Kingdom citizens due to his intolerance towards anything happy or comical"},
];
